Add description how to use developer tools in AME
eclipse-esmf/esmf-aspect-model-editor pull request #170
Opened 2024-03-14 18:35 UTC by michelu89

2024-03-14 18:36 UTC, larisaVasile approved these changes

2024-03-15 14:53 UTC, chris-volk requested changes

2024-03-18 08:08 UTC, michelu89 commented on documentation/ame-guide/modules/ROOT/pages/support/support.adoc
> +To close the Developer Tools, simply click on the 'X' icon located on the right-hand side of the Developer Tools menu bar.
Yes, its the same everywhere.

2024-03-18 08:09 UTC, michelu89 commented on documentation/ame-guide/modules/ROOT/pages/support/support.adoc
> +* For Windows Users: Press *Control+Shift+I* on your keyboard to open the Developer Tools.
You mean the "start" on Control+Shift+I ?
If yes it is for bold.

2024-03-20 12:51 UTC, merged